package com.saurabhshcs.adtech.microservices.designpattern.saga.ecommerce.domain;
public enum OrderStatus {
    PENDING, PAYMENT_PROCESSING, PAYMENT_COMPLETED, PAYMENT_FAILED,
    INVENTORY_RESERVED, INVENTORY_FAILED, SHIPPING_SCHEDULED, SHIPPING_FAILED,
    COMPLETED, COMPENSATING, COMPENSATION_COMPLETED, FAILED
}
